volumes:
  pg_fleet:

services:
  fleet_db:
    container_name: fleet-app-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: fleet_username
      POSTGRES_PASSWORD: fleet_password
      POSTGRES_DB: fleet_db
    volumes:
      - pg_fleet:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: fleet-app
    restart: always
    depends_on:
      - fleet_db
    environment:
      DB_URL: jdbc:postgresql://fleet_db:5432/fleet_db

  front:
    build:
      context: ./frontend-vuetify
    container_name: fleet-front
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt