
spring:
  application:
    name: "PROD"
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetoverviewdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8088
  max-http-request-header-size: 100MB
