spring:
  application:
    name: "Fleet Overview"
  profiles:
    active: "dev"

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  show-actuator: true
  override-with-generic-response: false
