spring:
  config:
    import: "optional:file:./backend/.env[.properties]"
  application:
    name: "Fleet Management"
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 5
      auto-commit: true
  mvc:
    problemdetails:
      enabled: true

  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: always

  jpa:
    show_sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

server:
  port: ${SERVER_PORT}
  max-http-request-header-size: 100MB
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB
    connection-timeout: 20s
    threads:
      max: 10

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${ISSUER}
    access-token-ttl: ${ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${REFRESH_TOKEN_TTL}

mybatis:
  mapper-locations: classpath*:db/sqlMaps/**/*.xml

  configuration:
    log-prefix: "_MYBATIS_"

telegram:
  token: ${TOKEN}
  chatIds: ${REPORT_CHAT_ID}
  logging:
    chatId: ${LOGS_CHATS}

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  receiver: ${MAIL_RECEIVER}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

resource:
  path: "//root//resources//"

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLE}
    path: /v3/api-docs

  swagger-ui:
    enabled: ${SWAGGER_ENABLE}