spring:
  application:
    name: "Fleet Overview"
  profiles:
    active: "prod"

  threads:
    virtual:
      enabled: true
server:
  tomcat:
    threads:
      max: 10

mybatis:
  mapper-locations:
    - "classpath*:/db/sqlMaps/**/*.xml"
    - "classpath*:/db/sqlMaps/*.xml"
  config-location: classpath:mybatis-config.xml

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  show-actuator: true
  override-with-generic-response: false
