spring:
  application:
    name: "PROD"
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8088
  max-http-request-header-size: 100MB
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 50MB
    connection-timeout: 20s
    threads:
      max: 200
      min-spare: 10

telegram:
  token: "6174384781:AAENYCRflrXFt6KERjQC1LhW6yd_zs-7Vbc"
  chatIds: "-1002554948125"
mail:
  senders: "info@efficientmanllc.com,sardorbekmatniyazov03@gmail.com"
  host: smtp.timeweb.ru
  port: 2525
  username: "bilol@efficientmanllc.com"
  password: "if2u25pcf7"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
resource:
  path: "d:\\resources\\"

logging:
  file:
    name: fleet.log
  level:
    root: INFO
