spring:
  application:
    name: "PROD"
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8088
  max-http-request-header-size: 100MB
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 50MB
    connection-timeout: 20s
    threads:
      max: 200
      min-spare: 10

telegram:
  token: "6174384781:AAENYCRflrXFt6KERjQC1LhW6yd_zs-7Vbc"
  chatIds: "-1002554948125"
mail:
  senders: ""
  host: smtp.gmail.com
  username: sardorbekmatniyazov03@gmail.com
  password: "rdlv svgm wzmn ymbx"

resource:
  path: "/home/seco/resources/"

logging:
  file:
    name: fleet.log
  level:
    root: INFO
